### ISSUE TITLE
Generate a TOML string from an appropriate Racket value

### ISSUE THREAD

**Issue by winny-** [toml-racket/toml-racket#2]
There should be a way to print out the canonical TOML for a given jsexpr.

**Comment by bzyeung** [comment]
I'm pretty close to ready to put together a pull request for this.  There's still a few kinks to work out, but I'm optimistic I'll be able to reserve enough time to get them sorted out this weekend.

One broader point that I feel is worth a chance for input has to do with the handling of values that do not satisfy `jsexpr?`, such as dates and some numbers.  In order to facilitate using toml-test for encoders, the goal I've been striving for is to try to satisfy toml-test while taking a strict superset of `(hash/c symbol? jsexpr?)` as input.

An alternative approach could be to automatically parse strings (such as interpreting the string `"nan"` as the value `+nan.0` or similar).  It's also possible to have multiple related encoding functions.

**Comment by winny-** [comment]
It seems there might be a strong overlap between JSON and TOML.  Not all valid (Racket) TOML expressions may be jsexprs.  This indicates this overlap isn't perfect.  

To fix this imperfect overlap, I suggest that we create a new predicate `tomlexpr?` that returns `#t` if the Racket value can be serialized into a TOML document (much like `jsexpr?` for JSON documents).  With `tomlexpr?` we can then create a contracted function `tomlexpr->string` to take a Racket value (a `tomlexpr?`) and convert it into a string.

I might be missing something.

**Comment by bzyeung** [comment]
> It seems there might be a strong overlap between JSON and TOML. Not all valid (Racket) TOML expressions may be jsexprs. 

Correct.  jsexprs can't have dates, infinities, or NaN, while these are all explicitly defined (with non-string syntax) in the TOML spec.  So every jsexpr that is a hash can also be unambiguously represented by a valid TOML doc, but the reverse is not true.  However, jsexprs can be values without keys, where that can't be represented in a TOML doc.

> I suggest that we create a new predicate `tomlexpr?` that returns `#t` if the Racket value can be serialized into a TOML document (much like `jsexpr?` for JSON documents). With `tomlexpr?` we can then create a contracted function `tomlexpr->string` to take a Racket value (a `tomlexpr?`) and convert it into a string.

It sounds like we're on the same page.  This is the approach I was taking, and I think I have a working (but ugly) prototype.  I still have to update the docs and scripts, and I'd like to do some cleanup.  But it does work!  🎉
