### ISSUE TITLE
Full toml-test compliance

### ISSUE THREAD

**Issue by winny-** [toml-racket/toml-racket#6]
- [x] literal strings `'like this'`
- [x] multiline strings `"""like this"""`
- [x] multiline literal strings `'''like this'''`
- [x] float parsing (?)
- [x] inline tables `{ like = "this", and = "another" }`
- [x] handle table defined multiple times
- [x] local datetime, local date, and local time
- [x] Unicode escapes limited to \uXXXX and \UXXXXXXXX

**Comment by bzyeung** [comment]
Handling for all of the string types, local datetimes, and inline tables is addressed in the current state of #9, along with a bugfix regarding the handling of cases where the final line ends in EOF instead of newline.  (That bugfix was more or less addressed as part of the inline table implementation.)  For the most part, these changes had a relatively clear path forward without making significant changes to the basic parsing framework.  I may open an issue to come up with a more elegant solution to the EOF bugfix, but I wanted to wait until we resolved the duplicate table feature, as there's a potential decision point there that may affect this as well.

The crux of the problem with the duplicate tables is that the current parser completely builds out each table at a given level before merging them.  Therefore, it has no way of distinguishing the following two cases, one of which is valid and one of which isn't.
```
# VALID
[a.b.c]
answer = 42

[a]
better = 43
```
```
# INVALID (a simpler test without the dotted keys is explicitly in the test suite)
[a]
b.c.answer = 42

[a]
better = 43
```
The existing duplication check requires the _entire tables_ to be `equal?`, which is why it would let something like the latter example through.  The current check is sufficient to address the case where all the tables are empty, as then they would trivially be exact duplicates.

The TOML spec doesn't include all the _contents_ of the table as part of "defining the table."  Thus the invalid example "defines" table `a` twice, even though its contents are disjoint.  That you can explicitly define a parent table even though "earlier" dotted keys implicitly define it (the valid example above) is because the ordering on the same level is specified not to matter.  As such, the valid example is equivalent to the case where the `a` definition occurs before the `a.b.c` definition.

So I see a couple of possibilities here.
1. Pass the explicitly defined keys along, so that a modified duplication check can have a go at them.  This is probably the simplest approach, but this could get tricky around where blocks end.  I haven't thought through all the permutations.
2. Delay inferring parent tables, then incorporate this into the inference/merge step.  This might be trickier, but would then allow us to get rid of the clunky duplication check that occurs immediately prior to merge.
3. Modify the parser to be more line-oriented instead of block-oriented.  This would (in my opinion) make the parser a little bit closer to the language of the TOML spec itself, which could result in a simpler final product, but this would be a relatively big overhaul.  Further, it's not clear to me that TOML won't eventually add the explicit notion of a block, as there seems to be some discussion of that in the TOML repo issues.

I'm probably going to take a shot at option (1) for a first go and see how gnarly it gets, but I'm open to other suggestions.
